### ISSUE TITLE
Make ERC 725 Identity & Operational Wallet Required

### ISSUE THREAD

**Issue by lukeskinner** [OriginTrail/node-interface#9]
(Reported on https://node-profile.origintrail.io/) 

A user on Discord has used the "Deposit ETH to your Operational Wallet" feature without entering either a ERC 725 Identity or Operational Wallet.

The code at https://github.com/OriginTrail/node-interface/blob/767d4c2bc01bf45019f89ce2cde0b62c72c714aa/src/components/DepositEth.vue#L51 
uses a ```sendTransaction``` api call. 

According to the documentation at https://web3js.readthedocs.io/en/1.0/web3-eth.html#sendtransaction

![image](https://user-images.githubusercontent.com/7475696/51575571-7d7b0a80-1eaa-11e9-98b2-27f5f29d4a1e.png)

If you don't provide a "to" address (which would be the operational wallet the user didn't enter) it does a contract creation transaction. As far as I can see there's no way of reclaiming the ETH sent to this contract because the contract code is hard coded to "0x" when it sends the transaction.

I think the login screen should make ERC 725/Operational wallet mandatory. The depositEth() method should also have a safety check on null/empty addresses. I could maybe write up the fixes for this at some point but I'm not familiar with vue.js. 

Not really related to the code but the user lost a small amount of ETH here, I can provide details privately if needed.

**Comment by lukeskinner** [comment]
Appears to be fixed on the website! Thanks for fixing it so quickly.

**Comment by lukeskinner** [comment]
![image](https://user-images.githubusercontent.com/7475696/51647049-255c0b00-1f73-11e9-8fad-532b02569fb8.png)

Hmm looks like the login screen has the validation but the operational wallet never loads regardless of what you put into it. You can't deposit or withdraw anything from what I can tell.

**Comment by tjosm** [comment]
I was also dumb enough to do this last month. I deposited ETH to my ERC-725 address.
https://etherscan.io/address/0x0db74fa921d6d6a4b99c05f4eafdfe9051125181

Is there any chance I can get them back?
